# Generated by Django 6.0.6 on 2026-07-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparacion',
            options={'verbose_name': 'Reparación', 'verbose_name_plural': 'Reparaciones'},
        ),
    ]
